### ISSUE TITLE
有错别字

### ISSUE THREAD

**Issue by jialangli** [the-web3/blockchain-wallet#42]
![1721213588207](https://github.com/user-attachments/assets/517d5c8a-906a-4f8f-8623-e40263a56c09)
钱包第二章的UTXO模型：在现实生活中，一笔转账对应的是一个付款人和一个收款人，而在比特币中，一笔转账对应的是多个转账人和多个收款人。

**Comment by guoshijiang** [comment]
可以提 PR 哈
